/**
 * @benchpress/contracts - Core TypeScript types and Enums
 */

export enum ExperimentState {
  RECEIVED = "RECEIVED",
  PLANNING = "PLANNING",
  PLAN_REJECTED = "PLAN_REJECTED",
  PLAN_APPROVED = "PLAN_APPROVED",
  DISPATCHING = "DISPATCHING",
  RUNNING = "RUNNING",
  AGGREGATING = "AGGREGATING",
  REJECTED = "REJECTED",
  ABSTAINED = "ABSTAINED",
  CANARY_PENDING = "CANARY_PENDING",
  CANARY_RUNNING = "CANARY_RUNNING",
  ROLLED_BACK = "ROLLED_BACK",
  RECOMMENDED = "RECOMMENDED",
  PUBLISHED = "PUBLISHED",
  FAILED_TERMINAL = "FAILED_TERMINAL",
}

export enum LogicalRunState {
  PENDING = "PENDING",
  CLAIMED = "CLAIMED",
  PROVIDER_RUNNING = "PROVIDER_RUNNING",
  VERIFYING = "VERIFYING",
  SUCCEEDED = "SUCCEEDED",
  FAILED_MODEL = "FAILED_MODEL",
  FAILED_ORACLE = "FAILED_ORACLE",
  FAILED_INFRA = "FAILED_INFRA",
  TIMED_OUT = "TIMED_OUT",
  BUDGET_EXCEEDED = "BUDGET_EXCEEDED",
  CANCELLED_BEFORE_START = "CANCELLED_BEFORE_START",
}

export enum PublicDecision {
  STAY = "STAY",
  TEST_MORE = "TEST MORE",
  SWITCH = "SWITCH",
}

export enum InternalOutcome {
  SWITCH_RECOMMENDED = "SWITCH_RECOMMENDED",
  STAY_CHEAPEST_FAILED = "STAY_CHEAPEST_FAILED",
  STAY_BASELINE_SUPERIOR = "STAY_BASELINE_SUPERIOR",
  ABSTAIN_INSUFFICIENT_EVIDENCE = "ABSTAIN_INSUFFICIENT_EVIDENCE",
  REJECTED_QUALITY_FLOOR = "REJECTED_QUALITY_FLOOR",
  REJECTED_BUDGET_EXCEEDED = "REJECTED_BUDGET_EXCEEDED",
  CANARY_ROLLED_BACK = "CANARY_ROLLED_BACK",
}

export enum TruthClass {
  BENCHPRESS_MEASURED = "BENCHPRESS_MEASURED",
  OFFICIAL_SPECIFICATION = "OFFICIAL_SPECIFICATION",
  PROJECTED = "PROJECTED",
  ILLUSTRATIVE = "ILLUSTRATIVE",
  DEMO_FIXTURE = "DEMO_FIXTURE",
}

export enum WorkflowPhase {
  RESEARCH_PLANNING = "RESEARCH_PLANNING",
  SPECIFICATION = "SPECIFICATION",
  EXECUTION = "EXECUTION",
  REVIEW = "REVIEW",
  REFINEMENT = "REFINEMENT",
  WHOLE_WORKFLOW = "WHOLE_WORKFLOW",
}

export enum RiskClass {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum LatencySensitivity {
  INTERACTIVE = "INTERACTIVE",
  NEAR_REALTIME = "NEAR_REALTIME",
  BATCH = "BATCH",
  BACKGROUND = "BACKGROUND",
}

export enum FailureReason {
  NONE = "NONE",
  TIMEOUT = "TIMEOUT",
  MAX_TURNS_EXCEEDED = "MAX_TURNS_EXCEEDED",
  BUDGET_EXCEEDED = "BUDGET_EXCEEDED",
  ORACLE_ASSERTION_FAILED = "ORACLE_ASSERTION_FAILED",
  SYNTAX_ERROR = "SYNTAX_ERROR",
  RUNTIME_EXCEPTION = "RUNTIME_EXCEPTION",
  INFRASTRUCTURE_ERROR = "INFRASTRUCTURE_ERROR",
  PROVIDER_ERROR = "PROVIDER_ERROR",
  CANCELLED = "CANCELLED",
}

export enum EventType {
  MODEL_RELEASE = "MODEL_RELEASE",
  PRICE_CHANGE = "PRICE_CHANGE",
  REASONING_UPGRADE = "REASONING_UPGRADE",
  DEPRECATION_NOTICE = "DEPRECATION_NOTICE",
  MANUAL_TRIGGER = "MANUAL_TRIGGER",
  SCHEDULED_SWEEP = "SCHEDULED_SWEEP",
}

export enum SourceKind {
  PROVIDER_CATALOG = "PROVIDER_CATALOG",
  PRICE_INDEX = "PRICE_INDEX",
  ADMIN_CONSOLE = "ADMIN_CONSOLE",
  WEBHOOK = "WEBHOOK",
  SYNTHETIC_REPLAY = "SYNTHETIC_REPLAY",
}

export enum UncertaintyMethod {
  WILSON_SCORE = "WILSON_SCORE",
  BOOTSTRAP_PERCENTILE = "BOOTSTRAP_PERCENTILE",
  NOT_COMPUTED_SMALL_SAMPLE = "NOT_COMPUTED_SMALL_SAMPLE",
}

export enum StalenessReason {
  MODEL_SNAPSHOT_UPGRADED = "MODEL_SNAPSHOT_UPGRADED",
  PRICE_INDEX_CHANGED = "PRICE_INDEX_CHANGED",
  TOOL_SCHEMA_MUTATED = "TOOL_SCHEMA_MUTATED",
  BENCHMARK_TASK_REVISED = "BENCHMARK_TASK_REVISED",
  QUALITY_REGRESSION_DETECTED = "QUALITY_REGRESSION_DETECTED",
  MANUAL_INVALIDATION = "MANUAL_INVALIDATION",
}

// Invariant State Transition Matrix
export const VALID_EXPERIMENT_TRANSITIONS: Record<ExperimentState, ReadonlySet<ExperimentState>> = {
  [ExperimentState.RECEIVED]: new Set([ExperimentState.PLANNING, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.PLANNING]: new Set([ExperimentState.PLAN_APPROVED, ExperimentState.PLAN_REJECTED, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.PLAN_APPROVED]: new Set([ExperimentState.DISPATCHING, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.PLAN_REJECTED]: new Set([ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.DISPATCHING]: new Set([ExperimentState.RUNNING, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.RUNNING]: new Set([ExperimentState.AGGREGATING, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.AGGREGATING]: new Set([
    ExperimentState.REJECTED,
    ExperimentState.ABSTAINED,
    ExperimentState.CANARY_PENDING,
    ExperimentState.FAILED_TERMINAL,
  ]),
  [ExperimentState.CANARY_PENDING]: new Set([ExperimentState.CANARY_RUNNING, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.CANARY_RUNNING]: new Set([
    ExperimentState.ROLLED_BACK,
    ExperimentState.RECOMMENDED,
    ExperimentState.FAILED_TERMINAL,
  ]),
  [ExperimentState.REJECTED]: new Set([ExperimentState.PUBLISHED, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.ABSTAINED]: new Set([ExperimentState.PUBLISHED, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.ROLLED_BACK]: new Set([ExperimentState.PUBLISHED, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.RECOMMENDED]: new Set([ExperimentState.PUBLISHED, ExperimentState.FAILED_TERMINAL]),
  [ExperimentState.PUBLISHED]: new Set([]), // Terminal
  [ExperimentState.FAILED_TERMINAL]: new Set([]), // Terminal
};

export const VALID_RUN_TRANSITIONS: Record<LogicalRunState, ReadonlySet<LogicalRunState>> = {
  [LogicalRunState.PENDING]: new Set([LogicalRunState.CLAIMED, LogicalRunState.CANCELLED_BEFORE_START]),
  [LogicalRunState.CLAIMED]: new Set([LogicalRunState.PROVIDER_RUNNING, LogicalRunState.FAILED_INFRA]),
  [LogicalRunState.PROVIDER_RUNNING]: new Set([
    LogicalRunState.VERIFYING,
    LogicalRunState.FAILED_MODEL,
    LogicalRunState.TIMED_OUT,
    LogicalRunState.BUDGET_EXCEEDED,
    LogicalRunState.FAILED_INFRA,
  ]),
  [LogicalRunState.VERIFYING]: new Set([
    LogicalRunState.SUCCEEDED,
    LogicalRunState.FAILED_ORACLE,
    LogicalRunState.TIMED_OUT,
    LogicalRunState.FAILED_INFRA,
  ]),
  [LogicalRunState.SUCCEEDED]: new Set([]),
  [LogicalRunState.FAILED_MODEL]: new Set([]),
  [LogicalRunState.FAILED_ORACLE]: new Set([]),
  [LogicalRunState.FAILED_INFRA]: new Set([]),
  [LogicalRunState.TIMED_OUT]: new Set([]),
  [LogicalRunState.BUDGET_EXCEEDED]: new Set([]),
  [LogicalRunState.CANCELLED_BEFORE_START]: new Set([]),
};
