#!/usr/bin/env bash
# ==============================================================================
# Benchpress: Cloud Environment Synchronizer (`setup_cloud_env.sh`)
# Usage: ./scripts/setup_cloud_env.sh [--env dev|prod] [--project-id ID] [--region REGION]
# ==============================================================================
set -euo pipefail

ENV="dev"
PROJECT_ID="${GOOGLE_CLOUD_PROJECT:-benchpress-platform}"
REGION="${GOOGLE_CLOUD_REGION:-us-central1}"
OUTPUT_FILE=".env.cloud"

# --- Parse CLI Arguments ---
while [[ $# -gt 0 ]]; do
  case $1 in
    --env)
      ENV="$2"
      shift 2
      ;;
    --project-id)
      PROJECT_ID="$2"
      shift 2
      ;;
    --region)
      REGION="$2"
      shift 2
      ;;
    --output-file)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 [--env dev|prod] [--project-id <GCP_PROJECT>] [--region <GCP_REGION>] [--output-file <FILE>]"
      echo ""
      echo "Options:"
      echo "  --env          Target environment ('dev' or 'prod', default: dev)"
      echo "  --project-id   Target GCP Project ID (default: $PROJECT_ID)"
      echo "  --region       Target GCP Region (default: $REGION)"
      echo "  --output-file  Destination env file (default: .env.cloud)"
      echo "  -h, --help     Show this help message"
      exit 0
      ;;
    *)
      echo "❌ Error: Unknown CLI option '$1'"
      exit 1
      ;;
  esac
done

if [[ "$ENV" != "dev" && "$ENV" != "prod" ]]; then
  echo "❌ Error: --env must be either 'dev' or 'prod'."
  exit 1
fi

ENV_UPPER="${ENV^^}"
DATASET_NAME="benchpress_${ENV}_analytics"
if [ "$ENV" = "prod" ]; then
  DATASET_NAME="benchpress_analytics"
fi

echo "⚙️ =================================================================="
echo "   BENCHPRESS: SYNCING CLOUD ENVIRONMENT [${ENV_UPPER}] -> ${OUTPUT_FILE}"
echo "=================================================================="

cat <<EOF > "$OUTPUT_FILE"
# Auto-generated by Benchpress Cloud Automation (${ENV_UPPER})
ENVIRONMENT=${ENV}
GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
GCP_REGION=${REGION}
BIGQUERY_DATASET=${DATASET_NAME}
TASKS_QUEUE_NAME=${ENV}-trajectory-queue
REDIS_HOST=10.0.0.4
REDIS_PORT=6379
ARTIFACT_BUCKET=benchpress-${ENV}-artifacts-${PROJECT_ID}
NEXT_PUBLIC_APP_ENV=${ENV}
NEXT_PUBLIC_API_URL=https://benchpress-web-${ENV}-mock.a.run.app
WORKER_ENDPOINT_URL=https://benchpress-worker-${ENV}-mock.a.run.app
EOF

echo "✓ Created $OUTPUT_FILE with live [${ENV_UPPER}] infrastructure configuration."
