/**
 * Curated 18-Turn Multi-Agent SWE-bench Swarm Execution Trace
 * Real-time collaboration trace for django__django-11099
 */

import { SwarmMessageEnvelope, SwarmMetrics } from "./swarm-types";

export const MOCK_SWARM_MESSAGES: SwarmMessageEnvelope[] = [
  {
    id: "msg-01",
    turnNumber: 1,
    timestamp: "10:00:00.120",
    fromAgent: "ARCHITECT",
    toAgent: "ALL",
    actionType: "PLAN",
    content:
      "Ingested SWE-bench task django__django-11099. Problem statement: UsernameValidator allows trailing newline due to ^/$ regex anchors. Parsing AST for django/core/validators.py...",
    tokenCostUsd: 0.0052,
    tokensIncurred: 1420,
    targetFile: "django/core/validators.py",
  },
  {
    id: "msg-02",
    turnNumber: 2,
    timestamp: "10:00:00.640",
    fromAgent: "FINOPS_SENTINEL",
    toAgent: "ALL",
    actionType: "SENTINEL_AUDIT",
    content:
      "Initial FinOps Audit: Hard budget cap set to $2.00 USD. Workload profile: SWE_BENCH. Initializing token velocity tracker at baseline.",
    tokenCostUsd: 0.0001,
    tokensIncurred: 120,
  },
  {
    id: "msg-03",
    turnNumber: 3,
    timestamp: "10:00:01.180",
    fromAgent: "ARCHITECT",
    toAgent: "CODER",
    actionType: "PLAN",
    content:
      "Formulated 3-phase execution plan. Phase 1: Inspect lines 40–60 of django/core/validators.py to confirm ASCIIUsernameValidator and UnicodeUsernameValidator regex definitions.",
    tokenCostUsd: 0.0084,
    tokensIncurred: 2200,
    targetFile: "django/core/validators.py",
  },
  {
    id: "msg-04",
    turnNumber: 4,
    timestamp: "10:00:01.820",
    fromAgent: "CODER",
    toAgent: "SANDBOX",
    actionType: "TOOL_CALL",
    content: "Calling readFile(path='django/core/validators.py') inside isolated gVisor tmpfs worktree.",
    tokenCostUsd: 0.0008,
    tokensIncurred: 310,
    targetFile: "django/core/validators.py",
  },
  {
    id: "msg-05",
    turnNumber: 5,
    timestamp: "10:00:02.340",
    fromAgent: "CODER",
    toAgent: "ARCHITECT",
    actionType: "TOOL_RESULT",
    content:
      "readFile returned 21 lines. Found: regex = r'^[\\w.@+-]+$' at line 48 in ASCIIUsernameValidator and line 54 in UnicodeUsernameValidator.",
    tokenCostUsd: 0.0012,
    tokensIncurred: 650,
    targetFile: "django/core/validators.py",
    targetLine: 48,
  },
  {
    id: "msg-06",
    turnNumber: 6,
    timestamp: "10:00:02.920",
    fromAgent: "VOICE_COPILOT",
    toAgent: "DEVELOPER",
    actionType: "VOICE_DIAGNOSTIC",
    content:
      "Spoken Copilot: 'Architect identified regex anchoring bug on lines 47–55 in validators.py. In Python 3.7+, caret and dollar allow trailing newlines. Switching to backslash-A and backslash-Z will strictly anchor the string.'",
    tokenCostUsd: 0.0015,
    tokensIncurred: 450,
    targetFile: "django/core/validators.py",
    targetLine: 48,
  },
  {
    id: "msg-07",
    turnNumber: 7,
    timestamp: "10:00:03.540",
    fromAgent: "ARCHITECT",
    toAgent: "CODER",
    actionType: "PLAN",
    content:
      "Phase 2 Directive: Replace regex = r'^[\\w.@+-]+$' with regex = r'\\A[\\w.@+-]+\\Z' in both ASCII and Unicode validator classes.",
    tokenCostUsd: 0.0042,
    tokensIncurred: 1100,
    targetFile: "django/core/validators.py",
  },
  {
    id: "msg-08",
    turnNumber: 8,
    timestamp: "10:00:04.120",
    fromAgent: "CODER",
    toAgent: "SANDBOX",
    actionType: "TOOL_CALL",
    content:
      "Attempting edit_file(file_path='django/core/validators.py', old_content='^[\\\\w.@+-]+$', new_content='\\\\A[\\\\w.@+-]+\\\\Z')",
    tokenCostUsd: 0.0009,
    tokensIncurred: 420,
    targetFile: "django/core/validators.py",
  },
  {
    id: "msg-09",
    turnNumber: 9,
    timestamp: "10:00:04.680",
    fromAgent: "SUPERVISOR_HEALER",
    toAgent: "CODER",
    actionType: "HEAL_PATCH",
    content:
      "⚡ Schema Error Intercepted! edit_file is a deprecated alias and arguments [file_path, old_content, new_content] are mismatched. Synthesizing in-memory dynamic wrapper for editHunk(path, target_content, replacement_content). Injected into runtime in 142ms!",
    tokenCostUsd: 0.0018,
    tokensIncurred: 580,
    isSelfHealingEvent: true,
    targetFile: "django/core/validators.py",
    codeDiff: {
      path: "django/core/validators.py",
      target_content: "    regex = r'^[\\w.@+-]+$'",
      replacement_content: "    regex = r'\\A[\\w.@+-]+\\Z'",
      lines: "47-55",
      diffHunk:
        "--- django/core/validators.py (original)\n+++ django/core/validators.py (healed)\n@@ -45,7 +45,7 @@\n class ASCIIUsernameValidator(validators.RegexValidator):\n-    regex = r'^[\\w.@+-]+$'\n+    regex = r'\\A[\\w.@+-]+\\Z'\n     message = _('Enter a valid username.')",
    },
  },
  {
    id: "msg-10",
    turnNumber: 10,
    timestamp: "10:00:05.310",
    fromAgent: "CODER",
    toAgent: "SANDBOX",
    actionType: "TOOL_CALL",
    content:
      "Re-dispatching healed editHunk payload. Capturing Git-Tree Saga snapshot pre-mutation (SHA: 99a812f).",
    tokenCostUsd: 0.0005,
    tokensIncurred: 220,
    targetFile: "django/core/validators.py",
  },
  {
    id: "msg-11",
    turnNumber: 11,
    timestamp: "10:00:05.940",
    fromAgent: "CODER",
    toAgent: "ARCHITECT",
    actionType: "TOOL_RESULT",
    content:
      "Hunk replaced cleanly in django/core/validators.py. AST syntax validation passed. 0 syntax errors.",
    tokenCostUsd: 0.0006,
    tokensIncurred: 260,
    targetFile: "django/core/validators.py",
    targetLine: 48,
    codeDiff: {
      path: "django/core/validators.py",
      target_content: "    regex = r'^[\\w.@+-]+$'",
      replacement_content: "    regex = r'\\A[\\w.@+-]+\\Z'",
      lines: "47-55",
    },
  },
  {
    id: "msg-12",
    turnNumber: 12,
    timestamp: "10:00:06.580",
    fromAgent: "FINOPS_SENTINEL",
    toAgent: "ALL",
    actionType: "SENTINEL_AUDIT",
    content:
      "🛡️ Turn-5 Markov Token Velocity Check: Cumulative spend $0.0242 USD. Projected total cost $0.031 USD vs median CPR $0.42 USD. Trajectory highly efficient. Tier approved: Gemini 3.5 Flash.",
    tokenCostUsd: 0.0001,
    tokensIncurred: 140,
  },
  {
    id: "msg-13",
    turnNumber: 13,
    timestamp: "10:00:07.120",
    fromAgent: "ARCHITECT",
    toAgent: "CODER",
    actionType: "PLAN",
    content:
      "Phase 3 Directive: Execute test suite tests/auth_tests/test_validators.py -k test_username_validators_newline inside gVisor container.",
    tokenCostUsd: 0.0035,
    tokensIncurred: 920,
  },
  {
    id: "msg-14",
    turnNumber: 14,
    timestamp: "10:00:07.780",
    fromAgent: "CODER",
    toAgent: "SANDBOX",
    actionType: "TOOL_CALL",
    content: "Calling runPytest(test_path='tests/auth_tests/test_validators.py')",
    tokenCostUsd: 0.0007,
    tokensIncurred: 280,
  },
  {
    id: "msg-15",
    turnNumber: 15,
    timestamp: "10:00:08.520",
    fromAgent: "CODER",
    toAgent: "ALL",
    actionType: "TOOL_RESULT",
    content:
      "Pytest Assertion Suite Succeeded: 14 passed in 0.42s! test_ascii_username_validator_newline PASSED, test_unicode_username_validator_newline PASSED. 0 regressions.",
    tokenCostUsd: 0.0011,
    tokensIncurred: 540,
  },
  {
    id: "msg-16",
    turnNumber: 16,
    timestamp: "10:00:09.180",
    fromAgent: "VOICE_COPILOT",
    toAgent: "DEVELOPER",
    actionType: "VOICE_DIAGNOSTIC",
    content:
      "Spoken Copilot: 'Test assertions verified! All 14 test cases passed with zero regressions. Total spend was 2.4 cents, achieving a 96.7% cost reduction compared to monolithic frontier baselines.'",
    tokenCostUsd: 0.0012,
    tokensIncurred: 380,
  },
  {
    id: "msg-17",
    turnNumber: 17,
    timestamp: "10:00:09.840",
    fromAgent: "CICD_DAEMON",
    toAgent: "DEVELOPER",
    actionType: "PR_CREATED",
    content:
      "🤖 Autonomous Remediation: Branch created fix/django-11099-username-newline. Commit signed with Benchpress KMS GPG key (SHA256: 8821fa9b). Pull Request opened: #11099 [BENCHPRESS-AUTO] Fix ASCII/Unicode username validator newline bypass (CPR: $0.0245, Pass@1: 100%).",
    tokenCostUsd: 0.0014,
    tokensIncurred: 490,
  },
  {
    id: "msg-18",
    turnNumber: 18,
    timestamp: "10:00:10.420",
    fromAgent: "ARCHITECT",
    toAgent: "ALL",
    actionType: "PLAN",
    content:
      "✨ Swarm Resolution Complete: Trajectory TR-88219 finalized. Pass@1 Verified: TRUE. Total turns: 18 (4 reasoning cycles). Final Gross Spend: $0.0245 USD. FSM transitioning to COMPLETE.",
    tokenCostUsd: 0.0019,
    tokensIncurred: 620,
  },
];

export const INITIAL_SWARM_METRICS: SwarmMetrics = {
  totalTurns: 18,
  totalCostUsd: 0.0245,
  cprUsd: 0.0245,
  tokenVelocityKps: 1.42,
  activeAgent: "ARCHITECT",
  selfHealingCount: 1,
  passAt1: true,
  bloatRatioPct: 4.2,
  status: "COMPLETE",
};
