/**
 * Curated 12-Model SWE-bench & Multi-Benchmark Leaderboard Dataset.
 */

import { ModelLeaderboardEntry } from "./types";

export const BENCHMARK_MODELS: ModelLeaderboardEntry[] = [
  // 1. Benchpress Golden Hybrid Choreography (Gemini 2.5 Pro + Flash)
  {
    model_id: "hybrid-gemini-pro-flash",
    name: "Benchpress 2-Tier (Gemini 2.5 Pro + Flash)",
    provider: "Benchpress Hybrid",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 0.185,
    pass_at_1: 0.712,
    trajectory_bloat_ratio: 1.12,
    mean_latency_sec: 14.6,
    ast_healing_success_rate: 0.942,
    is_pareto_frontier: true,
    context_window_tokens: 1000000,
    price_per_1m_input: 0.45,
    price_per_1m_output: 1.85,
  },
  // 2. Google Gemini 2.5 Pro
  {
    model_id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 0.58,
    pass_at_1: 0.738,
    trajectory_bloat_ratio: 1.25,
    mean_latency_sec: 22.4,
    ast_healing_success_rate: 0.915,
    is_pareto_frontier: true,
    context_window_tokens: 1000000,
    price_per_1m_input: 1.25,
    price_per_1m_output: 5.0,
  },
  // 3. Google Gemini 2.5 Flash
  {
    model_id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 0.048,
    pass_at_1: 0.584,
    trajectory_bloat_ratio: 1.08,
    mean_latency_sec: 8.2,
    ast_healing_success_rate: 0.864,
    is_pareto_frontier: true,
    context_window_tokens: 1000000,
    price_per_1m_input: 0.075,
    price_per_1m_output: 0.3,
  },
  // 4. Anthropic Claude 3.7 Sonnet (Thinking)
  {
    model_id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet (Thinking)",
    provider: "Anthropic",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 1.48,
    pass_at_1: 0.742,
    trajectory_bloat_ratio: 1.42,
    mean_latency_sec: 32.8,
    ast_healing_success_rate: 0.892,
    is_pareto_frontier: false,
    context_window_tokens: 200000,
    price_per_1m_input: 3.0,
    price_per_1m_output: 15.0,
  },
  // 5. Anthropic Claude 3.5 Haiku
  {
    model_id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    provider: "Anthropic",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 0.38,
    pass_at_1: 0.521,
    trajectory_bloat_ratio: 1.35,
    mean_latency_sec: 11.5,
    ast_healing_success_rate: 0.821,
    is_pareto_frontier: false,
    context_window_tokens: 200000,
    price_per_1m_input: 0.8,
    price_per_1m_output: 4.0,
  },
  // 6. OpenAI o3-mini (High Reasoning)
  {
    model_id: "o3-mini",
    name: "o3-mini (High Reasoning)",
    provider: "OpenAI",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 0.89,
    pass_at_1: 0.695,
    trajectory_bloat_ratio: 1.68,
    mean_latency_sec: 28.5,
    ast_healing_success_rate: 0.884,
    is_pareto_frontier: false,
    context_window_tokens: 200000,
    price_per_1m_input: 1.1,
    price_per_1m_output: 4.4,
  },
  // 7. OpenAI GPT-4o
  {
    model_id: "gpt-4o",
    name: "GPT-4o (Omni)",
    provider: "OpenAI",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 1.32,
    pass_at_1: 0.648,
    trajectory_bloat_ratio: 1.74,
    mean_latency_sec: 21.0,
    ast_healing_success_rate: 0.812,
    is_pareto_frontier: false,
    context_window_tokens: 128000,
    price_per_1m_input: 2.5,
    price_per_1m_output: 10.0,
  },
  // 8. OpenAI GPT-4.5 Preview
  {
    model_id: "gpt-4.5-preview",
    name: "GPT-4.5 Preview",
    provider: "OpenAI",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 8.45,
    pass_at_1: 0.751,
    trajectory_bloat_ratio: 1.31,
    mean_latency_sec: 38.0,
    ast_healing_success_rate: 0.902,
    is_pareto_frontier: false,
    context_window_tokens: 128000,
    price_per_1m_input: 75.0,
    price_per_1m_output: 150.0,
  },
  // 9. DeepSeek V3
  {
    model_id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 0.16,
    pass_at_1: 0.598,
    trajectory_bloat_ratio: 1.48,
    mean_latency_sec: 18.2,
    ast_healing_success_rate: 0.795,
    is_pareto_frontier: true,
    context_window_tokens: 64000,
    price_per_1m_input: 0.14,
    price_per_1m_output: 0.28,
  },
  // 10. DeepSeek R1 (Distill 70B)
  {
    model_id: "deepseek-r1-70b",
    name: "DeepSeek R1 (70B)",
    provider: "DeepSeek",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 0.42,
    pass_at_1: 0.655,
    trajectory_bloat_ratio: 1.82,
    mean_latency_sec: 36.4,
    ast_healing_success_rate: 0.841,
    is_pareto_frontier: false,
    context_window_tokens: 64000,
    price_per_1m_input: 0.55,
    price_per_1m_output: 2.19,
  },
  // 11. Meta Llama 3.3 70B Instruct
  {
    model_id: "llama-3.3-70b",
    name: "Llama 3.3 70B Instruct",
    provider: "Meta",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 0.29,
    pass_at_1: 0.542,
    trajectory_bloat_ratio: 1.55,
    mean_latency_sec: 16.5,
    ast_healing_success_rate: 0.778,
    is_pareto_frontier: false,
    context_window_tokens: 128000,
    price_per_1m_input: 0.4,
    price_per_1m_output: 0.9,
  },
  // 12. Meta Llama 3.1 405B
  {
    model_id: "llama-3.1-405b",
    name: "Llama 3.1 405B",
    provider: "Meta",
    task_suite: "SWE_BENCH_VERIFIED",
    cpr_usd: 1.85,
    pass_at_1: 0.682,
    trajectory_bloat_ratio: 1.62,
    mean_latency_sec: 34.0,
    ast_healing_success_rate: 0.852,
    is_pareto_frontier: false,
    context_window_tokens: 128000,
    price_per_1m_input: 2.4,
    price_per_1m_output: 2.4,
  },
];
